name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push-my-java-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push my-java-app image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t luk14n/demo-my-java-app:latest -f Dockerfile -t luk14n/demo-my-java-app:latest .

          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push luk14n/demo-my-java-app:latest

  build-and-push-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push mysql image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t luk14n/mysql:latest -f Dockerfile -t luk14n/mysql:latest .

          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push luk14n/mysql:latest
